CHANGED: Bump to version 2.0.0 for consistency with other Elastix-2 packages ADDED: Add VTigerCRM schema to compatibility database files ADDED: Add the new task of reading the MySQL root password for the newly installed system, and storing it in /etc/mysql.conf , and requesting a password for the 'admin' login in Elastix, FreePBX, A2Billing, VTiger. This requires dialog to be installed in the system.

diff --git a/additionals/trunk/elastix-firstboot/elastix-firstboot b/additionals/trunk/elastix-firstboot/elastix-firstboot
--- a/additionals/trunk/elastix-firstboot/elastix-firstboot
+++ b/additionals/trunk/elastix-firstboot/elastix-firstboot
@@ -13,10 +13,6 @@
 # Source networking configuration.
 . /etc/sysconfig/network
 
-
-# TODO: place in config file?
-elastix_root_password="eLaStIx.2oo7"
-
 # extract value of a MySQL option from config files
 # Usage: get_mysql_option SECTION VARNAME DEFAULT
 # result is returned in $result
@@ -39,30 +35,153 @@ errlogfile="$result"
 get_mysql_option mysqld_safe pid-file "/var/run/mysqld/mysqld.pid"
 mypidfile="$result"
 
+BACKTITLE="Elastix password configuration"
+PASSWD_PATH="/etc/elastix.conf"
+OPTFILE="/tmp/option.$$"
+
 elastix_mysql_init(){
-	# Try to unconditionally set the root password. This will only succeed
-	# for the case where the root password is not set (as is the case on 
-	# first boot).
-	/usr/bin/mysqladmin -u root password "$elastix_root_password" 2>/dev/null
-	/usr/bin/mysqladmin -u root -h `hostname` password "$elastix_root_password" 2>/dev/null
+	# Check if process has been already done
+	FIRSTBOOT=0
+	if [ ! -e $PASSWD_PATH ] ; then
+		# Prompt for the MySQL password for this system
+		FIRSTBOOT=1
+		elastix_prompt_mysql_passwd
+		ret=$?
+		if [ $ret -ne 0 ] ; then
+	    	return $ret
+		fi
+	else
+	    echo "Password configuration already present."
+	fi
+
+	# Read the MySQL root password for this system
+	elastix_root_password=`grep mysqlrootpwd= /etc/elastix.conf | sed 's/^mysqlrootpwd=//'`
 
 	# The scripts placed in /var/spool/elastix-mysqldbscripts should be executed now.
 	ret=0
 	for dbscript in /var/spool/elastix-mysqldbscripts/*.sql ; do
-		echo "Applying MySQL script $dbscript ..."
 		if [ -e $dbscript ]; then
+			echo "Applying MySQL script $dbscript ..."
 			mysql -u root -p$elastix_root_password < $dbscript
 			ret=$?
 		fi
-	        if [ $ret -ne 0 ] ; then
-                	return $ret
+        if [ $ret -ne 0 ] ; then
+            	return $ret
 		else
 			# Remove just-executed script
 			rm -f $dbscript
-        	fi
+       	fi
 	done
 
+	if [ $FIRSTBOOT -ne 0 ] ; then
+		# Prompt for web passwords on first boot
+		elastix_prompt_web_passwd
+		ret=$?
+	fi
+
 	return $ret
+}
+
+elastix_prompt_mysql_passwd(){
+	dialog --backtitle "$BACKTITLE" --msgbox "The following screen will now ask for a password for the 'root' account of MySQL" 10 40
+	
+	# Read and set new MySQL root password
+	while [ "$MYSQL_PASSWD1" == "" ] ; do
+	    MYSQL_PASSWD1=""
+	    MYSQL_PASSWD2=""
+	    while [ "$MYSQL_PASSWD1" == "" ] ; do
+	        dialog --backtitle "$BACKTITLE" --insecure --passwordbox "Enter new MySQL root password" 10 60 2>$OPTFILE
+	        MYSQL_PASSWD1=`cat $OPTFILE`
+	        if [ "$MYSQL_PASSWD1" == "" ] ; then
+	            dialog --backtitle "$BACKTITLE" --msgbox "MySQL root password must be nonempty" 7 40
+	        fi
+	    done
+	    while [ "$MYSQL_PASSWD2" == "" ] ; do
+	        dialog --backtitle "$BACKTITLE" --insecure --passwordbox "Enter new MySQL root password again" 10 60 2>$OPTFILE
+	        MYSQL_PASSWD2=`cat $OPTFILE`
+	    done
+	    if [ "$MYSQL_PASSWD1" != "$MYSQL_PASSWD2" ] ; then
+	        dialog --backtitle "$BACKTITLE" --msgbox "Password and confirmation do not match!" 7 40
+	        MYSQL_PASSWD1=""
+	        MYSQL_PASSWD2=""
+	    fi
+	done
+	rm -f $OPTFILE	
+	if ! /usr/bin/mysqladmin -u root password "$MYSQL_PASSWD1" ; then
+	    echo "Unable to set root password for MySQL - password already set or server not running!"
+	    return 1
+	fi
+	
+	echo "UPDATE mysql.user SET Password=PASSWORD('$MYSQL_PASSWD1') WHERE User='root';" | mysql -u root -p$MYSQL_PASSWD1
+	ret=$?
+	if [ $? -ne 0 ]; then
+	    echo "Unable to set root password (2) for MySQL - password already set or server not running!"
+	    return 1
+	fi
+	echo "FLUSH PRIVILEGES;" | mysql -u root -p$MYSQL_PASSWD1
+	echo "mysqlrootpwd=$MYSQL_PASSWD1" > $PASSWD_PATH
+}
+
+elastix_prompt_web_passwd() {
+	dialog --backtitle "$BACKTITLE" --msgbox "The following screen will now ask for a password for user 'admin' that will be used for: Elastix Web Login, FreePBX, VTiger, A2Billing" 10 40
+	
+	MYSQL_PASSWD1=`grep mysqlrootpwd= /etc/elastix.conf | sed 's/^mysqlrootpwd=//'`
+
+	# Read and set new FreePBX admin password. This procedure works with FreePBX 2.7.0
+	# This password will also be used for Elastix login, VTiger and A2Billing
+	while [ "$FREEPBX_PASSWD1" == "" ] ; do
+	    FREEPBX_PASSWD1=""
+	    FREEPBX_PASSWD2=""
+	    while [ "$FREEPBX_PASSWD1" == "" ] ; do
+	        dialog --backtitle "$BACKTITLE" --insecure --passwordbox "Enter new password for 'admin'" 10 60 2>$OPTFILE
+	        FREEPBX_PASSWD1=`cat $OPTFILE`
+	        if [ "$FREEPBX_PASSWD1" == "" ] ; then
+	            dialog --backtitle "$BACKTITLE" --msgbox "Admin password must be nonempty" 7 40
+	        fi
+	    done
+	    while [ "$FREEPBX_PASSWD2" == "" ] ; do
+	        dialog --backtitle "$BACKTITLE" --insecure --passwordbox "Enter new password for 'admin' again" 10 60 2>$OPTFILE
+	        FREEPBX_PASSWD2=`cat $OPTFILE`
+	    done
+	    if [ "$FREEPBX_PASSWD1" != "$FREEPBX_PASSWD2" ] ; then
+	        dialog --backtitle "$BACKTITLE" --msgbox "Password and confirmation do not match!" 7 40
+	        FREEPBX_PASSWD1=""
+	        FREEPBX_PASSWD2=""
+	    fi
+	done
+	rm -f $OPTFILE
+	
+	echo "UPDATE asterisk.ampusers SET password_sha1=sha1('$FREEPBX_PASSWD1') WHERE username = 'admin';" | mysql -u root -p$MYSQL_PASSWD1
+	ret=$?
+	if [ $? -ne 0 ]; then
+	    echo "Unable to set admin password for FreePBX !"
+	    return 1
+	fi
+	
+	# Set password for Elastix login. Requires sed, md5sum, sqlite3.
+	MD5HASH=`echo -n "$FREEPBX_PASSWD1" | md5sum | sed 's/^\(.\{32\}\)  -/\1/'`
+	sqlite3 /var/www/db/acl.db "UPDATE acl_user SET md5_password = 'MD5HASH' WHERE name = 'admin'"
+	
+	# Set password for A2Billing
+	echo "UPDATE mya2billing.cc_ui_authen SET password = '$FREEPBX_PASSWD1' WHERE login = 'admin';" | mysql -u root -p$MYSQL_PASSWD1
+	ret=$?
+	if [ $? -ne 0 ]; then
+	    echo "Unable to set admin password for A2Billing !"
+	    return 1
+	fi
+	
+	# Remove redundant root login from A2Billing
+	echo "DELETE FROM mya2billing.cc_ui_authen WHERE login = 'root';" | mysql -u root -p$MYSQL_PASSWD1
+	
+	# Set password for VTiger. This assumes the vtigercrm510 database is already created. 
+	# This procedure works for VTigerCRM 5.1.0
+	echo "UPDATE vtigercrm510.vtiger_users SET user_password = ENCRYPT('$FREEPBX_PASSWD1', CONCAT('\$1\$', SUBSTRING('$FREEPBX_PASSWD1' FROM 1 FOR 2), '\$')), user_hash = md5('$FREEPBX_PASSWD1') WHERE user_name = 'admin'" | mysql -u root -p$MYSQL_PASSWD1
+	ret=$?
+	if [ $? -ne 0 ]; then
+	    echo "Unable to set admin password for VTiger !"
+	    return 1
+	fi
+	return 0
 }
 
 start(){
