CHANGED: Additionals - elastix-fistboot/elastix-firstboot: Now the Firewall will be activated in the installations process

diff --git a/additionals/trunk/elastix-firstboot/elastix-firstboot b/additionals/trunk/elastix-firstboot/elastix-firstboot
--- a/additionals/trunk/elastix-firstboot/elastix-firstboot
+++ b/additionals/trunk/elastix-firstboot/elastix-firstboot
@@ -296,6 +296,27 @@ This screen will now ask for a password for user 'admin' that will be used for: 
 	return 0
 }
 
+elastix_activate_firewall(){
+	salida=1
+	dialog --backtitle "Elastix Firewall Settings" --ok-label "Continue" --msgbox "Firewall Rules will be activated by default after finishing the installation.\nIf you wish setting any configurations in your firewall rules can do it from elastix web interface:\nSecurity > Firewall > Firewall Rules." 10 70
+	if [ -f "/usr/share/elastix/privileged/fwconfig" ]; then
+		/usr/bin/elastix-helper fwconfig --load 2>&1
+		tmp=$?
+		if [ $tmp -eq 0 ]; then
+			sqlite3 /var/www/db/iptables.db "update tmp_execute set first_time = 0 ,exec_in_sys = 1" > /dev/null 2>&1
+			if [ $? -eq 0 ]; then 
+				echo "Firewall actived successfully."
+				salida=0
+			fi
+		else
+			echo "Firewall can't be actived. Please activated your Firewall from from elastix web interface: Security > Firewall > Firewall Rules."
+		fi
+	else
+		echo "Firewall can't be actived. Don't exits file /usr/share/elastix/privileged/fwconfig"
+	fi
+	return $salida
+}
+
 start(){
 	ret=0
 
@@ -308,6 +329,9 @@ start(){
 		echo "No running MySQL server has been found."
 		ret=1
 	fi
+
+	# Firewall will be activated by default, It action is independet from mysql script
+	elastix_activate_firewall
 
     [ $ret -eq 0 -a -d /var/lock/subsys ] && touch /var/lock/subsys/elastix-firstboot
 	return $ret
