CHANGED: Elastix-firstboot: Reverted some changes of commit 3415 on 3414 (elastix-firstboot script)

diff --git a/additionals/trunk/elastix-firstboot/elastix-firstboot b/additionals/trunk/elastix-firstboot/elastix-firstboot
--- a/additionals/trunk/elastix-firstboot/elastix-firstboot
+++ b/additionals/trunk/elastix-firstboot/elastix-firstboot
@@ -240,14 +240,31 @@ This screen will now ask for a password for user 'admin' that will be used for: 
 	
 	# Set password for A2Billing
         WHIRLPOOL=`php -r "echo hash('whirlpool','$FREEPBX_PASSWD1');"`
-        echo "UPDATE mya2billing.cc_ui_authen SET pwd_encoded='$WHIRLPOOL' WHERE login='admin';" | mysql -u root "-p$MYSQL_PASSWD1"
+        echo "UPDATE mya2billing.cc_ui_authen SET pwd_encoded='$WHIRLPOOL' WHERE login='admin' OR login='root';" | mysql -u root "-p$MYSQL_PASSWD1"
 	#echo "UPDATE mya2billing.cc_ui_authen SET password = '$FREEPBX_PASSWD1' WHERE login = 'admin';" | mysql -u root -p$MYSQL_PASSWD1
 	ret=$?
 	if [ $? -ne 0 ]; then
 	    echo "Unable to set admin password for A2Billing !"
 	    return 1
 	fi
-	
+
+    #preguntando si existe el usuario admin
+	echo "SELECT count(*) FROM mya2billing.cc_ui_authen WHERE login='admin';" | mysql -u root "-p$MYSQL_PASSWD1" > /tmp/mys2billingTest
+	ret=$?
+	if [ $? -ne 0 ]; then
+	  echo "Unable to find admin user for A2Billing !"
+	else
+	  rels=`sed -n '2p' "/tmp/mys2billingTest"`
+		if [ $rels -le 0 ]; then # si la count es menor o igual a 0 entonces no existe el usuario admin por lo tanto cambio el usuario root a admin
+		  echo "UPDATE mya2billing.cc_ui_authen SET login='admin' WHERE login='root';" | mysql -u root "-p$MYSQL_PASSWD1"
+		  echo "Updating user 'root' to 'admin' in A2billing"
+		else  # existe en usuario admin y por lo tanto elimino al usuario root
+		  echo "DELETE FROM mya2billing.cc_ui_authen WHERE login = 'root';" | mysql -u root "-p$MYSQL_PASSWD1"
+		  echo "User 'root' of A2billing has been deleted because exist user 'admin' as Administrator"
+		fi
+	fi
+	rm -rf /tmp/mys2billingTest
+
 	# Remove redundant root login from A2Billing
 	# echo "DELETE FROM mya2billing.cc_ui_authen WHERE login = 'root';" | mysql -u root -p$MYSQL_PASSWD1
 	
