New version of hardware_detector, which fixes configuration glitches when run in systems with Sangoma and non-Sangoma cards, and also imposes a saner ordering on driver loading.

diff --git a/additionals/trunk/usr/sbin/hardware_detector b/additionals/trunk/usr/sbin/hardware_detector
--- a/additionals/trunk/usr/sbin/hardware_detector
+++ b/additionals/trunk/usr/sbin/hardware_detector
@@ -1,55 +1,87 @@
 #!/bin/bash
-#Este script en realidad hace más que la detección:
-# 1.- Detecta
-# 2.- Configura
-# 3.- Levanta servicios 
+#  vim: set expandtab tabstop=4 softtabstop=4 shiftwidth=4:
+#  Codificación: UTF-8
+#  +----------------------------------------------------------------------+
+#  | Elastix version 1.6                                                  |
+#  | http://www.elastix.org                                               |
+#  +----------------------------------------------------------------------+
+#  | Copyright (c) 2006 Palosanto Solutions S. A.                         |
+#  +----------------------------------------------------------------------+
+#  | Cdla. Nueva Kennedy Calle E 222 y 9na. Este                          |
+#  | Telfs. 2283-268, 2294-440, 2284-356                                  |
+#  | Guayaquil - Ecuador                                                  |
+#  | http://www.palosanto.com                                             |
+#  +----------------------------------------------------------------------+
+#  | The contents of this file are subject to the General Public License  |
+#  | (GPL) Version 2 (the "License"); you may not use this file except in |
+#  | compliance with the License. You may obtain a copy of the License at |
+#  | http://www.opensource.org/licenses/gpl-license.php                   |
+#  |                                                                      |
+#  | Software distributed under the License is distributed on an "AS IS"  |
+#  | basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See  |
+#  | the License for the specific language governing rights and           |
+#  | limitations under the License.                                       |
+#  +----------------------------------------------------------------------+
+#  | The Original Code is: Elastix Open Source.                           |
+#  | The Initial Developer of the Original Code is PaloSanto Solutions    |
+#  +----------------------------------------------------------------------+
 
+# Script to automate detection and configuration of all telephony hardware on
+# this system. This script should modify the following files to include the
+# information on all the supported hardware:
+#   /etc/dahdi/system.conf
+#   /etc/asterisk/chan_dahdi.conf
+#   /etc/asterisk/dahdi-channels.conf
+# In addition, this script may optionally configure mISDN support.
 
 there_is_sangoma_card=false
 there_is_misdn_card=false
 null_redirect_verbose="&>/dev/null"
 
+# Check whether specified module is loaded, returns 0 on SUCCESS
 is_module_loaded()
 {
-        is_loaded=true;
-        /sbin/lsmod | /bin/grep -i "$1"  &>/dev/null
-
-        if [ $? != 0 ]; then #si me devuelce 0 es por que si hay modulos, caso contrario no encontro modulos
-                is_loaded=false
-        fi
-        echo $is_loaded
+    is_loaded=0;
+    /sbin/lsmod | /bin/grep -q -i "$1"
+    is_loaded=$?
+    return $is_loaded
 }
 
+# Check whether Asterisk is up and running, returns 0 on SUCCESS
 is_asterisk_loaded()
 {
-        is_loaded=true;
-        /sbin/service asterisk status | grep "is running"  &>/dev/null
-        if [ $? != 0 ]; then #si me devuelce 0 es por que esta arriba el servicio
-                is_loaded=false
-        fi
-        echo $is_loaded
+    is_loaded=0;
+    /sbin/service asterisk status  &>/dev/null
+    # The asterisk service will return 0 if the service is running
+    is_loaded=$?
+    return $is_loaded
 }
 
-options_help() {
-        echo >&2 "Options:"
-        echo >&2 "  -h: help"
-        echo >&2 "  -m: enable detection cards mISDN"
-        echo >&2 "  -t: enable detection cards sangoma"
-        echo >&2 "  -v: verbose"
+# Display help information
+options_help()
+{
+    cat >&2 <<HELP_END
+Options:
+    -h: help
+    -m: enable detection of mISDN cards
+    -t: enable detection of Sangoma cards
+    -v: verbose output
+HELP_END
 }
 
-
+# Process all known command-line options
 while getopts 'hmtv' arg
 do
         case "$arg" in
                 h) options_help; exit 0;;
-		m) there_is_misdn_card=true;;
+                m) there_is_misdn_card=true;;
                 t) there_is_sangoma_card=true;;
                 v) null_redirect_verbose="";;
                 *) echo >&2 "unknown parameter -$arg, Aborting"; options_help; exit 1;;
         esac
 done
 
+# Reject any unknown command-line options
 shift $(( $OPTIND-1 ))
 if [ $# != 0 ]; then
         echo >&2 "$0: too many parameters"
@@ -57,71 +89,127 @@ if [ $# != 0 ]; then
         exit 1
 fi
 
-####################################################################
-############################ Process Start #########################
-####################################################################
+echo -e "HWDETECT: Starting card detection..."
 
-echo -e "Starting detection cards ..."
-
-if [ `is_asterisk_loaded` = true ]; then
-	echo -e "Step 1: Stoping service asterisk ..." 
-	eval "/usr/sbin/amportal stop  $null_redirect_verbose"
+if is_asterisk_loaded ; then
+    echo -e "HWDETECT: Stopping Asterisk..."
+    eval "/usr/sbin/amportal stop  $null_redirect_verbose"
 fi
 
-if [ $? = 0 ] && [ `is_module_loaded "wanpipe"` = true ]; then
-	echo -e "Step 2: Unmounting modules sangoma ..."
-	echo -e "        Stoping service wanrouter ..."
+if [ $? = 0 ] && is_module_loaded "wanpipe" ; then
+	echo -e "HWDETECT: Unloading Sangoma modules and stopping wanrouter..."
 	eval "/sbin/service wanrouter stop  $null_redirect_verbose"
 fi
 
+if [ $? = 0 ] && is_module_loaded "dahdi" ; then
+	echo -e "HWDETECT: Unloading dahdi modules..."
+	eval "/sbin/service dahdi stop  $null_redirect_verbose"
+fi
+
 if [ $? = 0 ] && [ $there_is_misdn_card = false ]; then
-        echo -e "Step 3: Unmounting modules mISDN ..."
-        echo -e "         Stoping service mISDN ..."
+        echo -e "HWDETECT: Stopping and deactivating mISDN service..."
         eval "/sbin/service mISDN stop $null_redirect_verbose"
         eval "/sbin/chkconfig --level 2345 mISDN off $null_redirect_verbose"
 fi
 
-if [ $? = 0 ] && [ $there_is_sangoma_card = true ]; then
-	echo -e "Step 4: Detecting sangoma cards ..."
-	eval "/usr/sbin/wancfg_zaptel --silent  $null_redirect_verbose"
+# At this step, there should be no telephony modules loaded in the kernel
+if [ -e /proc/dahdi ] ; then
+	echo -e "HWDETECT: Retrying unloading of dahdi modules..."
+	eval "/sbin/service dahdi stop  $null_redirect_verbose"
+    if [ -e /proc/dahdi ] ; then
+        echo "HWDETECT: WARNING: could not unload all dahdi modules. Hardware detection might not work correctly.";
+    fi
 fi
 
-if [ $? = 0 ]; then
-	echo -e "Step 5: Detecting dahdi cards ..." 
-	eval "/usr/sbin/dahdi_genconf $null_redirect_verbose"
+# Clean out previous dahdi configuration. TODO: back up configuration instead...
+rm -f /etc/dahdi/system.conf /etc/asterisk/chan_dahdi.conf /etc/asterisk/dahdi-channels.conf
+
+# Detect and configure Sangoma cards first. As an artifact of this detection,
+# Sangoma cards will appear before any other card in the spans. This matches the
+# order in which the drivers are loaded on system boot.
+if [ $? = 0 ] ; then
+    if [ $there_is_sangoma_card = true ]; then
+        # This step is supposed to create /etc/dahdi/system.conf, see next comment.
+    	echo -e "HWDETECT: Detecting Sangoma cards ..."
+    	eval "/usr/sbin/wancfg_dahdi --silent  $null_redirect_verbose"
+    fi
 fi
 
-if [ $? = 0 ]; then
-	echo -e "Step 6: Mounting modules dahdi ..."
-	echo -e "        Starting service dahdi ..."
-	eval "/sbin/service dahdi start  $null_redirect_verbose"
+if [ ! -e /etc/dahdi/system.conf ] ; then
+    # This file must exist in order for dahdi service to work.
+    touch /etc/dahdi/system.conf
 fi
 
-if [ $? = 0 ] && [ $there_is_sangoma_card = true ] && [ `is_module_loaded "wanpipe"` = false ]; then
-	echo -e "Step 7: Mounting modules sangoma ..."
-	echo -e "        Restoring service wanrouter ..."
+# If a Sangoma card was configured, its corresponding module needs to be present
+# when detecting dahdi cards for configuration. This is because there is already
+# a (possibly partial) chan_dahdi.conf which specifies echo cancellers for spans.
+# The Sangoma modules should be loaded before other dahdi modules, otherwise
+# the configured span data might get assigned to a different card.
+if [ $? = 0 ] && [ $there_is_sangoma_card = true ] && ! is_module_loaded "wanpipe" ; then
+	echo -e "HWDETECT: Temporarily restarting wanrouter service..."
 	eval "/sbin/service wanrouter restart  $null_redirect_verbose"
 fi
 
-#if [ $? = 0 ]; then
-#	echo -e "Step 8: Generating configs files /etc/zaptel.conf y /etc/asterisk/zapata-channels.conf ..."
-#	/usr/sbin/genzaptelconf -x $genzaptelconf_verbose
-#fi
+# To detect the rest of the dahdi cards, dahdi_genconf relies on the corresponding
+# module to be loaded first in the kernel, and reported in the /proc/dahdi/
+# directory. The easiest way to achieve this is to run "service dahdi start",
+# which modprobes all the modules, even if not configured yet. For this to work,
+# /etc/dahdi/system.conf must exist at this step.
+if [ $? = 0 ]; then
+	echo -e "HWDETECT: Probing for dahdi modules..."
+	eval "/sbin/service dahdi start $null_redirect_verbose"
+fi
 
+# Now, dahdi_genconf will detect all of the supported dahdi cards.
+if [ $? = 0 ]; then
+	echo -e "HWDETECT: Generating configuration for detected dahdi cards..." 
+	eval "/usr/sbin/dahdi_genconf $null_redirect_verbose"
+fi
+
+# Unload and reload Sangoma and dahdi in order to match the boot order.
+if [ $? = 0 ] && is_module_loaded "wanpipe" ; then
+	eval "/sbin/service wanrouter stop  $null_redirect_verbose"
+fi
+if [ $? = 0 ] && is_module_loaded "dahdi" ; then
+	eval "/sbin/service dahdi stop  $null_redirect_verbose"
+fi
+if [ $? = 0 ] && [ $there_is_sangoma_card = true ] && ! is_module_loaded "wanpipe" ; then
+	echo -e "HWDETECT: Restarting wanrouter service..."
+	eval "/sbin/service wanrouter restart  $null_redirect_verbose"
+fi
+if [ $? = 0 ]; then
+	echo -e "HWDETECT: Restarting dahdi service..."
+	eval "/sbin/service dahdi start  $null_redirect_verbose"
+fi
+
+# Configure mISDN cards which do not use dahdi services
 if [ $? = 0 ] && [ $there_is_misdn_card = true ]; then
-        echo -e "Step 9: Detecting mISDN cards ..."
-        eval "/sbin/service mISDN scan $null_redirect_verbose"
-	echo -e "Step 10: Configuring mISDN cards ..."
+    echo -e "HWDETECT: Detecting mISDN cards ..."
+    eval "/sbin/service mISDN scan $null_redirect_verbose"
+	echo -e "HWDETECT: Configuring mISDN cards ..."
 	eval "/sbin/service mISDN config $null_redirect_verbose"
-	echo -e "Step 11: Mounting modules mISDN ..."
-	echo -e "         Starting service mISDN ..."
+	echo -e "HWDETECT: Restarting mISDN service..."
 	eval "/sbin/service mISDN start $null_redirect_verbose"
 	eval "/sbin/chkconfig --level 2345 mISDN on $null_redirect_verbose"
 fi
 
-if [ $? = 0 ]; then
-        echo -e "Step 12: Restoring service asterisk ..."
-        eval "/usr/sbin/amportal restart  $null_redirect_verbose"
+# When detecting Sangoma cards, the wancfg_dahdi utility writes a chan_dahdi.conf
+# file that does not #include dahdi-channels.conf, nor chan_dahdi_additional.conf. 
+# This breaks non-Sangoma channels and FreePBX support unless fixed here.
+# This implementation is NOT removing the channel configurations found in 
+# chan_dahdi.conf and placed there by wancfg_dahdi, but it seems that the 
+# channel configuration is harmless as repeated by dahdi-channels.conf.
+if ! grep -q -i "dahdi-channels.conf" /etc/asterisk/chan_dahdi.conf ; then
+    echo -e "HWDETECT: Fixing broken chan_dahdi.conf by adding required #includes..."
+    echo "#include chan_dahdi_additional.conf" >> /etc/asterisk/chan_dahdi.conf
+    echo "#include dahdi-channels.conf" >> /etc/asterisk/chan_dahdi.conf
 fi
 
-echo -e "End detection cards ..."
+if [ $? = 0 ]; then
+    echo -e "HWDETECT: Restarting asterisk service..."
+    eval "/usr/sbin/amportal restart  $null_redirect_verbose"
+fi
+
+
+echo -e "HWDETECT: End of card detection."
+
